# Generated by Django 3.0.3 on 2020-05-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cotle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='appcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apply',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_rec', to='Cotle.Recruit'),
        ),
    ]
