# Generated by Django 3.0.3 on 2020-05-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cotle', '0002_auto_20200522_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_app', to='Cotle.Apply')),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_rec', to='Cotle.Recruit')),
            ],
        ),
    ]
