# Generated by Django 3.0.3 on 2020-05-29 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cotle', '0003_auto_20200528_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='accept',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
